# Generated by Django 5.2.1 on 2025-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='is_valid',
            new_name='answer_word',
        ),
    ]
