# Generated by Django 5.2.1 on 2025-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_is_valid_word_answer_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='answer_word',
            new_name='answer',
        ),
    ]
