# Generated by Django 5.2.1 on 2025-06-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_answer_word_word_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['text']},
        ),
    ]
